### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by ajbraus** [koresar/medici#11]
Is there an example project of how this is used? I'm debating between this and using SQL.

**Comment by koresar** [comment]
I'm not an expert myself, but here is what I did to get started:
* You would need to be familiar with [double-entry accounting terminology](https://www.google.com/search?q=double-entry+accounting+terminology)
* You'd need a MongoDB
* When `require("medici")` is executed it creates Mongoose in-memory schemas. Nothing is created in the DB at this stage.
* Then you need to create a new Book. For example I keep a book per (crypto) currency: `const currencyBook = new medici.book("Flash-" + currency);`
* Then save your first entry:
```js
    const memo = "User cash deposit";
    const user = "john@example.com";
    const metaData = { userId: 123412341234, transactionId: 567856785678 };
    const creditAccount = "Assets:Morgan Bank";
    const debitAccount = "Liabilities:User";
    const amount = 1000.00;

    currencyBook.entry(memo + " : executed by : " + user)
        .credit(creditAccount, amount, metaData)
        .debit(debitAccount, amount * 0.99, metaData)
        .debit("MyFee", amount * 0.01, metaData)
        .commit();
```
* Get the accounts' balance:
```js
const myIncome = await currencyBook.balance({ account: "MyFee" });
const userBalance = await books.balance({ account: "Liabilities:User", user: userId });
```

I do not guarantee that any of the above code would work as is.

Was that something you were looking for?
