### ISSUE TITLE
Drop node 6 support, replace .then() with async/await

### ISSUE THREAD

**Issue by koresar** [koresar/medici#13]
Looking for a volunteer to do it.

* Drop node 6 support,
* replace `.then()` with `async/await`

**Comment by samuelt1** [comment]
I think I might do this, but how picky are you about pill requests? I have not contributed many times because the repository owner wanted all functions in alphabetical order.

**Comment by koresar** [comment]
> all functions in alphabetical order.

ahahahaha! I have never heard of such a thing in my life (except in C# world). :)

I'm not at all picky. Just don't break existing stuff. :)

Also, if you contribute a meaningful PR I'd love to make you a maintainer of medici.

**Comment by samuelt1** [comment]
sweet I will look into it then. I am going to use Medici then for my project. It will probably be like 1 month for my pull request, but I look forward to working with you.

**Comment by koresar** [comment]
I already like you! 😍

**Comment by koresar** [comment]
@samuelt1 any updates yet?

**Comment by samuelt1** [comment]
I got distracted with other things. I am just starting to use your module now

**Comment by koresar** [comment]
Typical situation. 😀

**Comment by koresar** [comment]
v4.0.0 was published. The only change - use async/await everywhere. Drop node.js 6 support.
