### ISSUE TITLE
meta data is not copied on voided Transactions

### ISSUE THREAD

**Issue by mos-flash** [koresar/medici#4]
Hi,

not sure if this library is still actively maintained. I believe I have come across a bug where transactions which have meta tags are not voided correctly. The extra ledger entry which is created to reverse the original transaction should have the same meta data as the original entries. if this is not the case - then balance queries based on meta tags are incorrect when a transaction has been voided.

The commit below shows a fix and updated test case. I also upgraded the version of a few libraries.

https://github.com/mos-flash/medici/commit/729253b673440e9b2d62d26299b9a293ffdce27b

I'm fairly new to JS and coffee script so feedback on changes is welcome.

**Comment by koresar** [comment]
@jraede hi there!

The project looks great, but unvisited for 4 years. I understand how that happens.

How about mos and I take ownership of the package, start maintaining it and upgrading, etc?

That would help the community greatly!

**Comment by jraede** [comment]
Works for me. I can transfer ownership to you in github. Do you know how to do that in npm?

Sent via Mobile

________________________________

**Comment by koresar** [comment]
That's awesome!
NPM is simple: https://docs.npmjs.com/cli/owner
Basically, `npm owner add koresar` inside the repo.

**Comment by koresar** [comment]
Some info about myself.
I lead this OSS - https://github.com/stampit-org/stampit 
and write about it sometimes - https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0
It consists of a dozen other modules - https://www.npmjs.com/~stamp

Mos and I work here: https://www.flash-fx.com/
We forked your awesome module, but we believe we can do a better effort by maintaining it publicly.

When would you have time to do the clicks?

**Comment by jraede** [comment]
@koresar should be all set.

**Comment by koresar** [comment]
Brilliant! Thank you so much.
We appreciate your help.

**Comment by koresar** [comment]
@jraede good news. v1.0.0 was published!
https://unpkg.com/medici@1.0.0/

See changes in the bottom of the README https://github.com/koresar/medici#changelog
Here is the PR involved: #5 

Thank you very much Jason for the great piece of code and the openness. :)
