### ISSUE TITLE
write is not a function

### ISSUE THREAD

**Issue by assemmarwan** [koresar/medici#7]
I have tried running the code snippet in the README but it says that "write is not a function". The code i tried is:

`const { book } = require('medici');`

`const myBook = new book('TEST');`

`myBook.entry('cool')`
   ` .debit('Assets:Cash', 1000)`
    `.credit('Income', 1000, { client: 'Sameer' })`
    `.write().then(result => {`
        `console.log(result);`
   ` });`

**Comment by koresar** [comment]
Ouch. Thanks mate!

I think it should be `commit()` instead. @assemmarwan could you please check if I am correct and maybe supply a PR? I'd be very thankful!

**Comment by koresar** [comment]
Fixed.
